### ISSUE TITLE
DOC: Conversion guide

### ISSUE THREAD

**Issue by pllim** [astropy/asdf-astropy#74]
If someone was already using `astropy.io.misc.asdf`, what do they need to do to use this new package? Even if it is a one-line import change, this should be documented.

**Comment by WilliamJamieson** [comment]
There is no change needed at all. The interface with 'asdf` used by `asdf-astropy` are given preference over the one used by `astropy.io.misc.asdf` (which will be eliminated with ASDF 3.0). Simply installing `asdf-astropy` is all one needs to do in order to use `asdf-astropy` to serialize the supported `astropy` objects using`asdf`.

Indeed, unless users are writing their own `asdf` extensions, they should never be importing `astropy.io.misc.asdf` or `asdf_astropy`. In the case that they are, we give clear instructions on how to create `asdf` extensions, to contribute to `asdf-astropy` [here](https://asdf-astropy.readthedocs.io/en/latest/asdf-astropy/example.html), or in general [here](https://asdf.readthedocs.io/en/latest/asdf/extending/extensions.html) in the general `asdf` documentation.

**Comment by pllim** [comment]
Maybe just re-iterate what you said above in the documentation under a section about `astropy.io.misc.asdf`?
